<P>Adds a country column based on the NUTS2 value to a dataframe.<br>It is used to plot NUTS2 by country.</p>

In [37]:
import pandas as pd
import pycountry
import numpy as np

In [38]:
csv_file = '/home/politti/data/Danube_5min/spei_nuts_2_1min/copula_analysis/nuts_2_copula_analysis.csv'

In [39]:
def get_country_name(code):
    try:
        # Convert code to uppercase to prevent matching failures
        country = pycountry.countries.get(alpha_2=str(code).upper())
        return country.name if country else "Unknown"
    except (AttributeError, ValueError):
        return "Unknown"

In [40]:
df = pd.read_csv(csv_file)
df.head(1)

,Return period,Hist_Duration_Thresh,Hist_Intensity_Thresh,Proj_Duration_Thresh,Proj_Intensity_Thresh,Ref_Joint_T,Proj_Joint_T,Likelihood_Change,Copula_Family_Ref,Copula_Family_Proj,...,dist_info_intensity_proj,Ref_duration_fit_score,Ref_intensity_fit_score,Proj_duration_fit_score,Proj_intensity_fit_score,scenario,gcm,spei,NUTS,reliability
0,1,-0.1,3.2,1.0,0.8,5.9,1.4,4.27,gumbel,gumbel,...,weibull_min,2,2,2,2,SSP3-7.0,UKESM1-0-LL,3,HU22,8

In [41]:
df['CNT'] = df['NUTS'].str[:2]
df.head(1)

,Return period,Hist_Duration_Thresh,Hist_Intensity_Thresh,Proj_Duration_Thresh,Proj_Intensity_Thresh,Ref_Joint_T,Proj_Joint_T,Likelihood_Change,Copula_Family_Ref,Copula_Family_Proj,...,Ref_duration_fit_score,Ref_intensity_fit_score,Proj_duration_fit_score,Proj_intensity_fit_score,scenario,gcm,spei,NUTS,reliability,CNT
0,1,-0.1,3.2,1.0,0.8,5.9,1.4,4.27,gumbel,gumbel,...,2,2,2,2,SSP3-7.0,UKESM1-0-LL,3,HU22,8,HU

In [42]:
df['Country'] = df['CNT'].apply(get_country_name)
df.head()

,Return period,Hist_Duration_Thresh,Hist_Intensity_Thresh,Proj_Duration_Thresh,Proj_Intensity_Thresh,Ref_Joint_T,Proj_Joint_T,Likelihood_Change,Copula_Family_Ref,Copula_Family_Proj,...,Ref_intensity_fit_score,Proj_duration_fit_score,Proj_intensity_fit_score,scenario,gcm,spei,NUTS,reliability,CNT,country
0,1,-0.1,3.2,1.0,0.8,5.9,1.4,4.27,gumbel,gumbel,...,2,2,2,SSP3-7.0,UKESM1-0-LL,3,HU22,8,HU,Hungary
1,5,-0.1,3.2,5.8,13.5,5.9,1.4,4.27,gumbel,gumbel,...,2,2,2,SSP3-7.0,UKESM1-0-LL,3,HU22,8,HU,Hungary
2,10,2.4,4.0,6.9,15.9,15.8,1.5,10.75,gumbel,gumbel,...,2,2,2,SSP3-7.0,UKESM1-0-LL,3,HU22,8,HU,Hungary
3,30,4.3,6.1,8.4,18.8,97.6,2.4,40.17,gumbel,gumbel,...,2,2,2,SSP3-7.0,UKESM1-0-LL,3,HU22,8,HU,Hungary
4,50,4.7,7.2,9.1,20.0,204.6,2.8,73.63,gumbel,gumbel,...,2,2,2,SSP3-7.0,UKESM1-0-LL,3,HU22,8,HU,Hungary

In [43]:
# df[df['country'] == 'Unknown'][['NUTS', 'CNT']]

xk_mask = df['CNT'] == 'XK'
df['Country'] = np.where(xk_mask,'Kosovo', df['Country'])

In [45]:
df['Country'] = df['Country'].replace({'Moldova, Republic of': 'Republic of Moldova'})

In [46]:
print(sorted(df.country.unique().tolist()) )

['Austria', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Czechia', 'Germany', 'Hungary', 'Kosovo', 'Montenegro', 'Republic of Moldova', 'Romania', 'Serbia', 'Slovakia', 'Slovenia', 'Switzerland', 'Ukraine']

In [47]:
df.to_csv(csv_file, index = False)